# Generated by Django 4.0 on 2023-11-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='lyricist',
        ),
    ]
