# Generated by Django 4.0 on 2023-11-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_songs_lyricist'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='photo',
            field=models.ImageField(default=True, upload_to='images'),
        ),
    ]
